# Customise this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile

# Change the syntax highlighting to Ruby

# All lines starting with a # are ignored when running `fastlane`

before_all do
  # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

  # sh "./customShellScript.sh"

  cocoapods

  # increment_build_number

  ipa({
    workspace: "DoubleNodeDemo.xcworkspace",
    configuration: "Debug",
    scheme: "DoubleNodeDemo",
  })

  # xctool
end

lane :test do
  snapshot
end

lane :beta do
  snapshot
  sigh
  deliver :skip_deploy, :beta
  # sh "your_script.sh"
end

lane :deploy do
  snapshot
  sigh
  deliver :skip_deploy, :force
  # frameit
end

lane :inhouse do
  # insert your code here
  say "It works"
end

lane :appstore do
    produce({
        produce_username: 'darren@doublenode.com',
        produce_app_identifier: 'com.doublenode.DoubleNodeDemo',
        produce_app_name: 'DoubleNodeDemo',
        produce_language: 'English',
        produce_version: '1.0',
        produce_sku: 123,
        produce_team_name: 'DoubleNode.com', # only necessary when in multiple teams
        produce_team_id: 'T864D3RXRZ' # only necessary when in multiple teams
    })

    deliver
end

# You can define as many lanes as you want

after_all do |lane|
  # This block is called, only if the executed lane was successful
  say "Successfully deployed new App Update for [App](http://link.com)."

  # slack({
  #   message: "Successfully deployed new App Update for [App](http://link.com).",
  #   success: true,
  #   channel: 'development'
  # })
end


error do |lane, exception|
  # Something bad happened
end